### ISSUE TITLE
Basic Report plugin:  Report folder is not created or displayed in the Test Explorer pane of Katalon Studio

### ISSUE THREAD

**Issue by DojoJoe** [katalon-studio/katalon-studio-basic-report-plugin#14]
Hi,
Yesterday, I also downloaded and installed Katalon Studio v.6.3.2 and installed the Basic Report plugin onto my Win10 64 bit computer. Running Chrome v.76.0.3809. I am also experiencing the same issue, where the Reports folder is not being created in the Test Explorer tree, after running my first Test Suite (see screenshots attached). Log View is showing the reports are being created in the C:directory, as EdWellDataLabs initally reported.
image

image

In addition to my previous report, I am wondering , is a Report folder is supposed to be created in the Test Explorer tree? Or, since this is a new plugin, that reports can only be found on the C: drive?

The Katalon store page nor the documentation are clear about this, and setup in Project Settings only checks for the report formats that will be created. Please advise.

**Comment by Padoplin** [comment]
Hello @DojoJoe 

I'm sorry for not responding earlier. Please see [this document](https://docs.katalon.com/katalon-studio/docs/basic-report.html#automatically-generate-reports) for a reply to your concern. 

Padoplin
