### ISSUE TITLE
Bug: Unable to export pdf 

### ISSUE THREAD

**Issue by tuananht** [katalon-studio/katalon-studio-basic-report-plugin#18]
Cause: `Image read failed.`

[log](https://drive.google.com/open?id=1rXs5xlaa5qE8j8UzlbtH90agHyY97xxB)

[project](https://drive.google.com/open?id=12GNXMEzcDagRXwmNvcNlCXoTj_QNCtGp)

**Comment by kms-loantran** [comment]
Error is still thrown when exporting the pdf report file.
Please download the sample project [here](https://drive.google.com/file/d/1ufmCVl-6rtmYjZHbeFWhMsGgFIuC1Ql4/view?usp=sharing).
  
<img width="1434" alt="Screen Shot 2019-09-19 at 11 25 07 AM" src="https://user-images.githubusercontent.com/29113513/65213425-5247ca00-dad0-11e9-986a-679befe2be18.png">
