### ISSUE TITLE
JUnit XML is only generated when CSV is selected

### ISSUE THREAD

**Issue by hhajni** [katalon-studio/katalon-studio-basic-report-plugin#3]
![image](https://user-images.githubusercontent.com/46674353/57712510-f62bef80-7670-11e9-93c8-28b879a3b84b.png)

The checkbox for JUnit is not connected properly in the listener, currently when CSV is selected, the CSV and the Junit xml are both generated, the JUnit checkbox doesn't work.

**Comment by duyluonganh** [comment]
Hi @hhajni,

Thanks for your report, we will update this soon.

**Comment by duyluonganh** [comment]
@NgocTMPhan Please verify

**Comment by duyluonganh** [comment]
@hhajni This fix has been released in v1.0.2. Please reload your plugin.

**Comment by hhajni** [comment]
@duyluonganh Thanks, it's working fine now.
