### ISSUE TITLE
Bug: [Windows] Cannot export PDF report when error message too long

### ISSUE THREAD

**Issue by NgocTMPhan** [katalon-studio/katalon-studio-basic-report-plugin#5]
Refer to this link:
https://forum.katalon.com/t/pdf-report-crashing-when-execution-fails/25790/15

**Comment by duyluonganh** [comment]
@NgocTMPhan Please test with the attachment
[katalon-studio-basic-report-plugin.zip](https://github.com/katalon-studio/katalon-studio-basic-report-plugin/files/3210563/katalon-studio-basic-report-plugin.zip)
